export enum SubjectStatus {
  SCREENED = 'SCREENED',
  ENROLLED = 'ENROLLED',
  COMPLETED = 'COMPLETED',
  WITHDRAWN = 'WITHDRAWN',
  LOST_TO_FOLLOWUP = 'LOST_TO_FOLLOWUP',
  DISCONTINUED = 'DISCONTINUED',
}
